// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJyYhyO9MwkJPuH4-YlJzJvkdHyr2VdEA',
    appId: '1:485865753530:android:b0bf0e1b9ad047c8bbeb83',
    messagingSenderId: '485865753530',
    projectId: 'academify-39811',
    storageBucket: 'academify-39811.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC44sOT6GC84nXpK8mYIMSKqMkJzHlBnU',
    appId: '1:485865753530:web:4a9006bfaa462606bbeb83',
    messagingSenderId: '485865753530',
    projectId: 'academify-39811',
    authDomain: 'academify-39811.firebaseapp.com',
    storageBucket: 'academify-39811.firebasestorage.app',
    measurementId: 'G-8HZ2N72Y3H',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC44sOT6GC84nXpK8mYIMSKqMkJzHlBnU',
    appId: '1:485865753530:web:9a4bf60705b50269bbeb83',
    messagingSenderId: '485865753530',
    projectId: 'academify-39811',
    authDomain: 'academify-39811.firebaseapp.com',
    storageBucket: 'academify-39811.firebasestorage.app',
    measurementId: 'G-HK8JY7Z2VK',
  );

}
